export const STOCKS_TIME_SERIES_DAILY = 'STOCKS_TIME_SERIES_DAILY';
export const STOCKS_TIME_SERIES_MONTHLY = 'STOCKS_TIME_SERIES_MONTHLY';
export const STOCKS_TIME_SERIES_WEEKLY = 'STOCKS_TIME_SERIES_WEEKLY';
export const MULTIPLE_STOCKS_SERIES_MONTHLY = 'MULTIPLE_STOCKS_SERIES_MONTHLY';

